//prawn
let pr1="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/prawn/1.png"
let pr2="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/prawn/2.png"
let pr3="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/prawn/3.png"
let pr4="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/prawn/4.png"
let pr5="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/prawn/5.png"
let pr6="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/prawn/6.png"
let pr7="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/prawn/7.png"
let pr8="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/prawn/8.png"
let pr9="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/prawn/9.png"
//coral
let cor1="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/cor/1.png"
let cor2="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/cor/2.png"
let cor3="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/cor/3.png"
let cor4="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/cor/4.png"
let cor5="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/cor/5.png"
let cor6="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/cor/6.png"
let cor7="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/cor/7.png"
let cor8="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/cor/8.png"
let cor9="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/cor/9.png"
//jelly
let jel1="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/jel/1.png"
let jel2="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/jel/2.png"
let jel3="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/jel/3.png"
let jel4="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/jel/4.png"
let jel5="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/jel/5.png"
let jel6="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/jel/6.png"
let jel7="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/jel/7.png"
let jel8="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/jel/8.png"
let jel9="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/jel/9.png"
//shell
let sh1="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/shel/1.png"
let sh2="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/shel/2.png"
let sh3="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/shel/3.png"
let sh4="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/shel/4.png"
let sh5="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/shel/5.png"
let sh6="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/shel/6.png"
let sh7="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/shel/7.png"
let sh8="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/shel/8.png"
let sh9="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/shel/9.png"
// rock
let ro1="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/rock/1.png"
let ro2="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/rock/2.png"
let ro3="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/rock/3.png"
let ro4="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/rock/4.png"
let ro5="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/rock/5.png"
let ro6="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/rock/6.png"
let ro7="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/rock/7.png"
let ro8="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/rock/8.png"
let ro9="https://cdn.jsdelivr.net/gh/botaro/blo@main/img/rock/9.png"
// oct
let oct1="https://cdn.jsdelivr.net/gh/botaoct/blo@main/img/oct/1.png"
let oct2="https://cdn.jsdelivr.net/gh/botaoct/blo@main/img/oct/2.png"
let oct3="https://cdn.jsdelivr.net/gh/botaoct/blo@main/img/oct/3.png"
let oct4="https://cdn.jsdelivr.net/gh/botaoct/blo@main/img/oct/4.png"
let oct5="https://cdn.jsdelivr.net/gh/botaoct/blo@main/img/oct/5.png"
let oct6="https://cdn.jsdelivr.net/gh/botaoct/blo@main/img/oct/6.png"
let oct7="https://cdn.jsdelivr.net/gh/botaoct/blo@main/img/oct/7.png"
let oct8="https://cdn.jsdelivr.net/gh/botaoct/blo@main/img/oct/8.png"
let oct9="https://cdn.jsdelivr.net/gh/botaoct/blo@main/img/oct/9.png"
//

